### PR TITLE
Change disableCache to enableCache variable name

### PR DESCRIPTION
**Pull request by mliradelc**
While testing the new `disableCache` feature, I realize that the naming is confusing. If `disableCache` is `true`, you should expect that the cache  is disabled, but it was on the another way around.

So I changed the name to `enableCache` easier to understand.

### CODE REVIEW

**Comment by ferserc1** [comment]
The name `disableCache` is chosen on purpose because it avoids compatibility issues. If the behavior were `enableCache`, updating paella-core without adding the parameter to the configuration would cause the HLS plugin to stop working as it did before the update.

Any change that modifies the operation of the library must be made in a major version, and adding the parameter in this way is the only way to do so while maintaining the same behavior.

**Comment by ferserc1** [comment]
I have been able to spend two minutes on this, and I just realized that it is possible to change the parameter name without modifying the API operation, if you modify the initialization of the configuration when the parameter is `undefined`.

```js
enableCache: config.enableCache === undefined ? true : false
```

Thus, if the configuration parameter is not defined, the default behavior is that the cache is active, and that does not modify the API.

The change is quite trivial, but as I have so many fronts open at the same time I didn't notice it when I saw the pull request. If you want you can modify it and I accept.

**Comment by mliradelc** [comment]
I can look into that, also,  if you want, I can change the order of preferences like I show you in my last comment and avoid any variable name change.

Tell me what you prefer 😄

**Comment by ferserc1** [comment]
I don't care about the variable name, the important thing is that if you use paella-core version 1.x, the behavior is not modified if you update the library without updating the configuration file.

**Comment by mliradelc** [comment]
In that case, `enableCache` is better, because it will be false when is not set in the config file.

**Comment by mliradelc** [comment]
I just updated the branch and solved the conflicts

**Pull request merged**
